Avoid error message related to missing debug files
Processing files: oml2-debuginfo-2.9.0rpmtest-1.1.x86_64
error: Could not open %files file /home/abuild/rpmbuild/BUILD/oml2-2.9.0rpmtest/debugfiles.list: No such file or directory

Signed-off-by: Olivier Mehani <olivier.mehani@nicta.com.au>